pipeline {
    agent {
        node {
            label 'bbl'
        }
    }

    environment{
        DOCKER_TAG = getDockerTag()
    }

    stages{

        stage('Build Image'){
            steps{
                 sh "docker build -f pipeline/Dockerfile . -t central-registry.bracbank.com:5000/api-testing-tool:${DOCKER_TAG}"
            }
        }
    }
}

def getDockerTag(){
    def tag = sh script: 'git rev-parse HEAD', returnStdout: true
    return tag
}
